version: '3'
services:
  db:
    image: postgres
    env_file:
     - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
