default: &default
  adapter: postgresql
  timeout: 5000
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] || 12345678 %>

development:
  <<: *default
  database: svora_bot_dev

test:
  <<: *default
  database: svora_bot_test


production:
  <<: *default
  database: svora_bot

